### ISSUE TITLE
发送#星铁收入时报错

### ISSUE THREAD

**Issue by YuYue-Amatsuki** [hewang1an/StarRail-plugin#18]
log如下
```JavaScript
0|Yunzai-Bot  | [YzBot][17:22:24.768][MARK] [星穹铁道][month][File Manager<$ǿĀD>(404 Not Found)] #星铁收入
0|Yunzai-Bot  | [YzBot][17:22:25.181][ERRO] [星穹铁道][month]
0|Yunzai-Bot  | [YzBot][17:22:25.182][ERRO] TypeError: Cannot read properties of null (reading 'saveId')
0|Yunzai-Bot  |     at Runtime.render (file:///home/yuyue/Yunzai-Bot/lib/plugins/runtime.js:150:20)
0|Yunzai-Bot  |     at hkrpg.month (file:///home/yuyue/Yunzai-Bot/plugins/StarRail-plugin/apps/hkrpg.js:181:21)
0|Yunzai-Bot  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
0|Yunzai-Bot  |     at async PluginsLoader.deal (file:///home/yuyue/Yunzai-Bot/lib/plugins/loader.js:274:52)
```

**Comment by YuYue-Amatsuki** [comment]
补充：发送#星铁卡片时不会正确显示玩家名和uid与所在服务器以及游戏内等级，但控制台无报错
![31e84abc333ab0ee.jpg](https://user-images.githubusercontent.com/86163024/235881645-8a47fcff-0b82-4c9b-ad44-10b354965a5d.jpg)

**Comment by TsukinaKasumi** [comment]
可能是没拿到数据吧，后续看看具体的原因，会尽快解决。
